"""add index

Revision ID: 19a50d406b67
Revises: 0c2c28b23e9f
Create Date: 2021-05-23 22:53:05.275787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a50d406b67'
down_revision = '0c2c28b23e9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_username_key', 'user', type_='unique')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    # ### end Alembic commands ###
